sudo: required
services:
  - docker

before_install:
  - docker build -t chhsu0222/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chhsu0222/react-test npm test

after_success:
  - docker build -t chhsu0222/multi-client ./client
  - docker build -t chhsu0222/multi-nginx ./nginx
  - docker build -t chhsu0222/multi-server ./server
  - docker build -t chhsu0222/multi-worker ./worker
